version: 0.2
phases:
  install:
    commands:
      - echo install step from code...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1 | sed 's|https://||')
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t employeerepo .
      - docker tag employeerepo:latest 328859930614.dkr.ecr.ap-south-1.amazonaws.com/employeeapi:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 328859930614.dkr.ecr.ap-south-1.amazonaws.com/employeeapi:latest
      - echo Writing image definitions file...
      - printf '[{"name":"EmpolyeeAPIContainer","imageUri":"%s"}]' 328859930614.dkr.ecr.ap-south-1.amazonaws.com/employeeapi:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json